### ISSUE TITLE
NameError: name 'owned' is not defined

### ISSUE THREAD

**Issue by PhungVui** [StephanAkkerman/Binance_Charts#1]
Help me ! this is error !

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Mr.Happy\Downloads\Binance_Charts-main\Binance_Charts-main\Binance_Charts.py", line 80, in animate
    symbol = owned[i]
NameError: name 'owned' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 806, in callit
    func(*args)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\_backend_tk.py", line 253, in idle_draw
    self.draw()
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\figure.py", line 1870, in draw
    self.canvas.draw_event(renderer)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backend_bases.py", line 1759, in draw_event
    self.callbacks.process(s, event)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 229, in process
    self.exception_handler(exc)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 81, in _exception_printer
    raise exc
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 224, in process
    func(*args, **kwargs)
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\animation.py", line 959, in _start
    self._init_draw()
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\animation.py", line 1703, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "C:\Users\Mr.Happy\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\animation.py", line 1726, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "C:\Users\Mr.Happy\Downloads\Binance_Charts-main\Binance_Charts-main\Binance_Charts.py", line 85, in animate
    if default[default_counter] not in owned:
NameError: name 'owned' is not defined

C:\Users\Mr.Happy\Downloads\Binance_Charts-main\Binance_Charts-main>python Binance_Charts.py

**Comment by StephanAkkerman** [comment]
Hi, thanks for bringing this to my attention. I have fixed this issue, if you fetch the updated code I just uploaded it should work fine again.

**Comment by PhungVui** [comment]
> Hi, thanks for bringing this to my attention. I have fixed this issue, if you fetch the updated code I just uploaded it should work fine again.

thank bro, i'm check again 👯
